import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:xml/xml.dart';

const _lime = '#C8F35A';
const _carbon = '#121C18';
const _white = '#F6F8F4';
const _outputDirectory = 'assets/branding/generated';
const _androidResources = 'android/app/src/main/res';
const _generatedNotice =
    'Generated by tool/generate_brand_assets.dart. Do not edit.';

/// Run from the repository root with:
/// `puro flutter test tool/generate_brand_assets.dart`.
/// Add `--dart-define=BRAND_CHECK=true` to verify without writing files.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('generate or verify the canonical Gpix brand assets', () async {
    const checkOnly = bool.fromEnvironment('BRAND_CHECK');
    final mark = _Artwork.read('mark', width: 256, height: 256);
    final wordmark = _Artwork.read('wordmark', width: 380, height: 144);
    const launcherMarkSize = 58.0;
    const splashMarkSize = 168.0;
    await _verifySafeAreas(
      mark,
      launcherMarkSize: launcherMarkSize,
      splashMarkSize: splashMarkSize,
    );
    final outputs = _Outputs(checkOnly: checkOnly);

    await outputs.export(
      'gpix-mark-lime',
      _svg(512, 512, mark.place(x: 0, y: 0, width: 512, color: _lime)),
      width: 512,
      height: 512,
    );
    await outputs.export(
      'gpix-mark-carbon',
      _svg(512, 512, mark.place(x: 0, y: 0, width: 512, color: _carbon)),
      width: 512,
      height: 512,
    );

    for (final dark in [true, false]) {
      await outputs.export(
        dark ? 'gpix-logo-on-dark' : 'gpix-logo-on-light',
        _svg(
          1200,
          400,
          '${mark.place(x: 168, y: 72, width: 256, color: dark ? _lime : _carbon)}\n'
          '${wordmark.place(x: 472, y: 94, width: 560, color: dark ? _white : _carbon)}',
        ),
        width: 1200,
        height: 400,
      );
    }

    // Store and legacy icons have no oversized adaptive-icon padding.
    final icon = _svg(
      1024,
      1024,
      mark.place(x: 122, y: 122, width: 780, color: _lime),
      background: _carbon,
    );
    await outputs.export('gpix-icon', icon, width: 1024, height: 1024);

    final splashLockup =
        '${mark.place(x: 200, y: 96, width: 320, color: _lime)}\n'
        '${wordmark.place(x: 150, y: 464, width: 420, color: _white)}';
    final transparentSplash = _svg(720, 720, splashLockup);
    await outputs.export(
      'gpix-splash-lockup',
      transparentSplash,
      width: 720,
      height: 720,
    );
    await outputs.export(
      'gpix-splash',
      _svg(
        1080,
        1920,
        '<g transform="translate(180 600)">\n$splashLockup\n</g>',
        background: _carbon,
      ),
      width: 1080,
      height: 1920,
    );

    for (final density in {
      'mdpi': 48,
      'hdpi': 72,
      'xhdpi': 96,
      'xxhdpi': 144,
      'xxxhdpi': 192,
    }.entries) {
      await outputs.write(
        '$_androidResources/mipmap-${density.key}/ic_launcher.png',
        await _png(icon, width: density.value, height: density.value),
      );
    }
    await outputs.write(
      '$_androidResources/drawable-nodpi/gpix_splash_lockup.png',
      await _png(transparentSplash, width: 720, height: 720),
    );
    await outputs.writeText(
      '$_androidResources/values/colors.xml',
      '<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- $_generatedNotice -->\n'
          '<resources>\n'
          '    <color name="gpix_carbon">$_carbon</color>\n'
          '    <color name="gpix_lime">$_lime</color>\n'
          '</resources>\n',
    );
    await outputs.writeText(
      '$_androidResources/drawable/gpix_launcher_foreground.xml',
      mark.androidVector(
        viewport: 108,
        markSize: launcherMarkSize,
        color: _lime,
      ),
    );
    await outputs.writeText(
      '$_androidResources/drawable/gpix_launcher_monochrome.xml',
      mark.androidVector(
        viewport: 108,
        markSize: launcherMarkSize,
        color: '#FFFFFF',
      ),
    );
    await outputs.writeText(
      '$_androidResources/drawable/gpix_splash_icon.xml',
      mark.androidVector(viewport: 288, markSize: splashMarkSize, color: _lime),
    );
    outputs.finish();
  }, timeout: const Timeout(Duration(minutes: 2)));
}

String _number(num value) =>
    value.toStringAsFixed(6).replaceFirst(RegExp(r'\.?0+$'), '');

String _svg(int width, int height, String content, {String? background}) =>
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- $_generatedNotice -->\n'
    '<svg xmlns="http://www.w3.org/2000/svg" width="$width" height="$height" '
    'viewBox="0 0 $width $height">\n'
    '${background == null ? '' : '<rect width="$width" height="$height" fill="$background"/>\n'}'
    '$content\n'
    '</svg>\n';

/// Store only canonical filled path data so every export uses the same shape.
class _Artwork {
  const _Artwork(this.width, this.paths);

  factory _Artwork.read(
    String name, {
    required int width,
    required int height,
  }) {
    final path = 'assets/branding/source/$name.svg';
    final document = XmlDocument.parse(File(path).readAsStringSync());
    final root = document.rootElement;
    if (root.name.local != 'svg' ||
        root.getAttribute('viewBox') != '0 0 $width $height') {
      throw FormatException('$path must have viewBox="0 0 $width $height".');
    }
    for (final attribute in root.attributes) {
      if (!{
        'xmlns',
        'width',
        'height',
        'viewBox',
        'role',
        'aria-labelledby',
        'aria-label',
      }.contains(attribute.name.qualified)) {
        throw FormatException(
          '$path has unsupported root attribute ${attribute.name}.',
        );
      }
    }
    final paths = <({String data, String fillRule})>[];
    for (final element in root.childElements) {
      if (element.name.local == 'title' || element.name.local == 'desc') {
        continue;
      }
      if (element.name.local != 'path' || element.childElements.isNotEmpty) {
        throw FormatException('$path must contain filled paths only.');
      }
      for (final attribute in element.attributes) {
        if (!{
          'd',
          'fill',
          'fill-rule',
          'id',
        }.contains(attribute.name.qualified)) {
          throw FormatException(
            '$path has unsupported path attribute ${attribute.name}.',
          );
        }
      }
      final data = element.getAttribute('d');
      final fillRule = element.getAttribute('fill-rule') ?? 'nonzero';
      if (data == null ||
          data.trim().isEmpty ||
          element.getAttribute('fill') == 'none' ||
          !{'nonzero', 'evenodd'}.contains(fillRule)) {
        throw FormatException('$path contains an invalid filled path.');
      }
      paths.add((data: data, fillRule: fillRule));
    }
    if (paths.isEmpty) {
      throw FormatException('$path must contain at least one filled path.');
    }
    return _Artwork(width, paths);
  }

  final int width;
  final List<({String data, String fillRule})> paths;

  String place({
    required double x,
    required double y,
    required double width,
    required String color,
  }) =>
      '<g transform="translate(${_number(x)} ${_number(y)}) '
      'scale(${_number(width / this.width)})">\n'
      '${paths.map((path) => _element('path', {'fill': color, 'fill-rule': path.fillRule, 'd': path.data})).join('\n')}\n'
      '</g>';

  String androidVector({
    required int viewport,
    required double markSize,
    required String color,
  }) {
    final scale = _number(markSize / width);
    final offset = _number((viewport - markSize) / 2);
    final content = paths
        .map(
          (path) => _element('path', {
            'android:fillColor': color,
            'android:fillType': path.fillRule == 'evenodd'
                ? 'evenOdd'
                : 'nonZero',
            'android:pathData': path.data,
          }),
        )
        .join('\n');
    return '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- $_generatedNotice -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="${viewport}dp" android:height="${viewport}dp"\n'
        '    android:viewportWidth="$viewport" android:viewportHeight="$viewport">\n'
        '    <group android:scaleX="$scale" android:scaleY="$scale"\n'
        '        android:translateX="$offset" android:translateY="$offset">\n'
        '$content\n'
        '    </group>\n'
        '</vector>\n';
  }
}

String _element(String name, Map<String, String> attributes) => XmlElement(
  XmlName.parts(name),
  attributes.entries.map(
    (attribute) => XmlAttribute(XmlName.parse(attribute.key), attribute.value),
  ),
).toXmlString();

Future<Uint8List> _png(
  String source, {
  required int width,
  required int height,
}) async {
  final image = await _render(source, width: width, height: height);
  try {
    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    if (data == null) {
      throw StateError('The Flutter engine could not encode a PNG.');
    }
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  } finally {
    image.dispose();
  }
}

Future<ui.Image> _render(
  String source, {
  required int width,
  required int height,
}) async {
  final picture = await vg.loadPicture(SvgStringLoader(source), null);
  try {
    final recorder = ui.PictureRecorder();
    ui.Canvas(recorder)
      ..scale(width / picture.size.width, height / picture.size.height)
      ..drawPicture(picture.picture);
    final scaledPicture = recorder.endRecording();
    try {
      return await scaledPicture.toImage(width, height);
    } finally {
      scaledPicture.dispose();
    }
  } finally {
    picture.picture.dispose();
  }
}

/// Include every partially covered pixel and its outside corner in the bound.
/// This keeps future master-artwork edits inside Android's circular safe areas.
Future<void> _verifySafeAreas(
  _Artwork mark, {
  required double launcherMarkSize,
  required double splashMarkSize,
}) async {
  const size = 1024;
  final source = _svg(
    size,
    size,
    mark.place(x: 0, y: 0, width: size.toDouble(), color: _lime),
  );
  final image = await _render(source, width: size, height: size);
  try {
    final data = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    if (data == null) {
      throw StateError('The Flutter engine could not inspect the mark.');
    }
    var maximumRadiusSquared = 0.0;
    for (var y = 0; y < size; y++) {
      for (var x = 0; x < size; x++) {
        if (data.getUint8((y * size + x) * 4 + 3) == 0) continue;
        final dx = x + 0.5 - size / 2;
        final dy = y + 0.5 - size / 2;
        maximumRadiusSquared = math.max(
          maximumRadiusSquared,
          dx * dx + dy * dy,
        );
      }
    }
    if (maximumRadiusSquared == 0) {
      throw StateError('The canonical mark is empty.');
    }
    final radiusRatio =
        (math.sqrt(maximumRadiusSquared) + math.sqrt(0.5)) / size;
    for (final area in [
      (name: 'adaptive launcher', markSize: launcherMarkSize, safeRadius: 33),
      (name: 'Android 12 splash', markSize: splashMarkSize, safeRadius: 96),
    ]) {
      if (radiusRatio * area.markSize > area.safeRadius) {
        throw StateError(
          'The canonical mark exceeds the ${area.name} safe circle. '
          'Reduce its generated mark size or adjust the source artwork.',
        );
      }
    }
  } finally {
    image.dispose();
  }
}

class _Outputs {
  _Outputs({required this.checkOnly});

  final bool checkOnly;
  final List<String> differences = [];
  int count = 0;

  Future<void> export(
    String name,
    String svg, {
    required int width,
    required int height,
  }) async {
    await writeText('$_outputDirectory/$name.svg', svg);
    await write(
      '$_outputDirectory/$name.png',
      await _png(svg, width: width, height: height),
    );
  }

  Future<void> writeText(String path, String text) =>
      write(path, utf8.encode(text));

  Future<void> write(String path, List<int> bytes) async {
    count++;
    final file = File(path);
    if (file.existsSync() && listEquals(await file.readAsBytes(), bytes)) {
      return;
    }
    differences.add(path);
    if (!checkOnly) {
      await file.parent.create(recursive: true);
      await file.writeAsBytes(bytes, flush: true);
    }
  }

  void finish() {
    if (checkOnly && differences.isNotEmpty) {
      fail(
        'Brand assets are missing or stale:\n${differences.join('\n')}\n'
        'Run: puro flutter test tool/generate_brand_assets.dart',
      );
    }
    stdout.writeln(
      checkOnly
          ? 'Verified $count brand assets.'
          : 'Generated $count brand assets (${differences.length} changed).',
    );
  }
}
