import 'dart:convert';
import 'dart:io';

/// Generate the UI adapter for locale-independent application message codes.
/// Flutter gen-l10n remains the source of all translated getters and ICU rules.
void main() {
  final catalog = jsonDecode(
    File('lib/l10n/app_en.arb').readAsStringSync(),
  ) as Map<String, dynamic>;
  final output = StringBuffer(
    '''// Generated by tool/generate_message_resolver.dart. Do not edit.
import '../domain/app_message.dart';
import '../l10n/generated/app_localizations.dart';

String resolveAppMessage(AppLocalizations l10n, AppMessage message,
    Object Function(Object?) argument) => switch (message.code) {
''',
  );
  for (final key in catalog.keys.where((key) => !key.startsWith('@'))) {
    final metadata = catalog['@$key'] as Map<String, dynamic>?;
    final placeholders =
        metadata?['placeholders'] as Map<String, dynamic>? ?? {};
    final args = <String>[];
    var index = 0;
    for (final value in placeholders.values) {
      final type = value['type'] ?? 'Object';
      args.add(
        type == 'Object'
            ? 'argument(message.arguments[$index])'
            : type == 'String'
            ? 'argument(message.arguments[$index]).toString()'
            : 'message.arguments[$index] as $type',
      );
      index++;
    }
    output.writeln(
      "  '$key' => l10n.$key${args.isEmpty ? '' : '(${args.join(', ')})'},",
    );
  }
  output.writeln('  _ => l10n.unexpectedError,\n};');
  File('lib/presentation/message_resolver.dart')
      .writeAsStringSync(output.toString());
}
